### ISSUE TITLE
Mod error in game

### ISSUE THREAD

**Issue by SGZ-Creations** [CJ-SPT/Skills-Extended#25] opened 2024-08-27 05:49 UTC
![lockpick bug](https://github.com/user-attachments/assets/715ca7c3-4642-459a-9dc5-8cb9781bf64a)
Not sure what more you would need 
Mod Version 1.3.0
SPT 3.9.8
Location: Lighthouse

**Comment by CJ-SPT** [comment] 2024-08-27 21:20
What key is this?

**Comment by SGZ-Creations** [comment] 2024-08-28 00:06
have no idea really just got the popup in the corner when i tried picking it

**Comment by SGZ-Creations** [comment] 2024-08-28 01:37
[2024.08.27_23-35-13_0.14.9.1.30626 errors.log](https://github.com/user-attachments/files/16773619/2024.08.27_23-35-13_0.14.9.1.30626.errors.log)
[2024.08.27_23-35-13_0.14.9.1.30626 traces.log](https://github.com/user-attachments/files/16773623/2024.08.27_23-35-13_0.14.9.1.30626.traces.log)

**Comment by SGZ-Creations** [comment] 2024-09-28 01:06
https://escapefromtarkov.fandom.com/wiki/USEC_cottage_room_key?file=Blue_Chalet_Garage_Second_Floor_Room_Door.png

**Comment by CJ-SPT** [comment] 2024-09-28 19:15
Im on hiatus from modding until I feel like working on things again.

**Comment by SGZ-Creations** [comment] 2024-10-01 23:15
ok i was just reporting my finding good luck have fun

**Comment by Agent772** [comment] 2024-10-03 18:31
I took a look at it and i could't reproduce that error and the door is entered in the config file in version 1.3.1. So maybe update your mod version :)

**Comment by SGZ-Creations** [comment] 2024-10-04 04:41
![image](https://github.com/user-attachments/assets/bb97f67d-e03b-4a97-9add-656f0cee3420)

well that was not mentioned to me as i have updated but that this post was on the fixed didn't get me. tho i have a other location for a bug like this


Mod version 1.3.1
Ground zero (Sandbox,  Sandbox_high)
![image](https://github.com/user-attachments/assets/07c566d1-89ad-4163-84e9-541523f8f9ef)
![image](https://github.com/user-attachments/assets/b01e0bc9-6883-458f-ac02-883c418e9ff1)

**Comment by Agent772** [comment] 2024-10-04 07:28
Someone reported that in the SPT Mod Support Thread, and i had a look into it:
[https://hub.sp-tarkov.com/forum/thread/4261-skills-extended/?postID=34479#post34479](SkillsExtendedModSupport)

Seams like, Sandbox_high doesnt get registered in the `LocationDoorIdLevels` Dictonary in:
[https://github.com/CJ-SPT/Skills-Extended/blob/d68f881baa55362ac7de139ea4e598753589236d/Plugin/LockPicking/LpHelpers.cs](Plugin/LockPicking/LpHelpers.cs)

that could be fixed with adding in Line 32:
`{"Sandbox_high", Plugin.SkillData.LockPicking.DoorPickLevels.GroundZero},`


But i currently lack the knowledge on how to recompile / build  that .dll new. So i can test it and make a Pull Request.

Maybe i find time on the weekend to learn that and test it, or someone with that skill reads that and does it :)

**Comment by CJ-SPT** [comment] 2024-10-04 11:01
You can't build this like a normal project. It has a special build process because of how I had to implement certain code to work. You must first build the pre-patcher. Add it to the game's patcher's folder, start the game, go into the bepinex menu, enable assembly dumping, restart the game, it will patch and dump the assembly to the bepinex folder, and you use the generated dumped assembly as the reference. Otherwise it will always fail to resolve certain references that I have added through the pre-patch.

**Closed** 2024-10-04 11:31 UTC
