### ISSUE TITLE
Can't use meds

### ISSUE THREAD

**Issue by kakahost** [CJ-SPT/Skills-Extended#9] opened 2024-07-21 08:28 UTC
![image](https://github.com/user-attachments/assets/f1e87793-c34e-459d-a08f-48d4def55299)

**Comment by CJ-SPT** [comment] 2024-07-22 05:43
Is this the 1.0.0 branch?

**Comment by kakahost** [comment] 2024-07-25 10:18
> Is this the 1.0.0 branch?

Yes, it is. Alpha 2

**Comment by Tetribyte** [comment] 2024-08-01 18:56
Looks to be due to a mod incompatibility. On a fresh install with only SkillsExtended, meds work as normal. So far Realism and UI Fixes seem to be fine. I’ll check other mods I have and see if something is causing this to throw an error.

**Comment by CJ-SPT** [comment] 2024-08-01 20:46
Its an intermitten issue I've been chasing down for over a week now. Its a bug that will effect any of the SE skills. My buffs are randomly going null for some reason. Have yet to be able to track down why. Also why there hasn't been an updated release since then.

**Comment by Tetribyte** [comment] 2024-08-01 21:08
Is that on the Client or Server side? I've been able to get errors from the client log and from the server log. Client side it is the "Object reference not set to instance of an object" and server side if the following.

`TypeError: Cannot read properties of undefined (reading '_id')
TypeError: Cannot read properties of undefined (reading '_id')
    at HealthController.offraidHeal (C:\snapshot\src\controllers\HealthController.ts:72:34)
    at HealthCallbacks.offraidHeal (C:\snapshot\src\callbacks\HealthCallbacks.ts:59:38)
    at HealthItemEventRouter.handleItemEvent (C:\snapshot\src\routers\item_events\HealthItemEventRouter.ts:33:45)
    at ItemEventRouter.handleEvents (C:\snapshot\src\routers\ItemEventRouter.ts:36:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ItemEventCallbacks.handleEvents (C:\snapshot\src\callbacks\ItemEventCallbacks.ts:22:31)
    at HttpRouter.handleRoute (C:\snapshot\src\routers\HttpRouter.ts:61:38)
    at HttpRouter.getResponse (C:\snapshot\src\routers\HttpRouter.ts:34:25)
    at SptHttpListener.getResponse (C:\snapshot\src\servers\http\SptHttpListener.ts:130:22)
    at IncomingMessage.<anonymous> (C:\snapshot\src\servers\http\SptHttpListener.ts:64:38)`

**Comment by CJ-SPT** [comment] 2024-08-01 21:13
Problem will be client side for sure. Best guess at the moment is it has something to do with events not properly being disposed of and re-subscribed to.

**Comment by Tetribyte** [comment] 2024-08-01 21:27
Is the SkillsExtended_PrePatch.dll needing to be in "BepInEx/patches"? When I was building out my own version of SkillsExtended, the mod was working, but was generating that file. Just tried it with a fresh install and was able to heal properly and gain experience. The patch is injecting the EBuffId for the skills into Tarkov's assembly, without it, that might be the null record issue.

**Comment by CJ-SPT** [comment] 2024-08-01 21:39
Its absolutely needed yes. Its a new requirement for 1.0.0. I'm injecting new enum fields for ease of use

**Comment by Tetribyte** [comment] 2024-08-01 21:40
That's not included in the mod download, so that might be the issue.

**Comment by CJ-SPT** [comment] 2024-08-02 21:35
Possibly fixed with dda861f267439bca94136ca769fb556481342db3 needs more testing to confirm

**Comment by CJ-SPT** [comment] 2024-08-04 06:55
Confirmed fixed.

**Closed by CJ-SPT** 2024-08-04 06:55 UTC
Labels: bug
